### ISSUE TITLE
Unable To Start The Program

### ISSUE THREAD

**Issue by Chahine2** [Buttys/ygopro#6]
This thing appears when i try to compile file, how to deal with it?
http://i.imgur.com/pHXgZ1o.png

**Comment by Buttys** [comment]
right click the ygo project and set as the start up project

**Comment by Chahine2** [comment]
Umm, Still the Same
![zeeer](https://cloud.githubusercontent.com/assets/6339408/5713904/caf050c0-9ac1-11e4-92c2-4a29739b875d.PNG)

**Comment by Chahine2** [comment]
Ok, i tried everything, am i Missing Something? 0..0

**Comment by sidschingis** [comment]
Did your ocgcore compile correctly?

**Comment by Chahine2** [comment]
In the beginning, Yes, but after this error's appearance, no.

**Comment by sidschingis** [comment]
Can you post your complete output when compiling?

**Comment by Chahine2** [comment]
Nothing appears in the output, just an annoying error message.
![trz](https://cloud.githubusercontent.com/assets/6339408/5726664/6339b218-9b5d-11e4-9af1-5b087d566985.PNG)

**Comment by sidschingis** [comment]
Check your build order and dependencies, ygopro needs to be build last.
Also try if you can compile only ocgcore.

**Comment by Chahine2** [comment]
No avail

**Comment by Chahine2** [comment]
Any help?

**Comment by sidschingis** [comment]
Try to only build ocgcore first and see if it compiles.
Also double check all your paths.

**Comment by Buttys** [comment]
Just delete your bin folder and recompile.
if you get the error unable to start ocgcore.lib that means you're trying to debug it and need to set ygo as the start up project. If you're still having issues try restarting your computer the file may be locked for some strange reason.

**Comment by Chahine2** [comment]
![pool](https://cloud.githubusercontent.com/assets/6339408/5740653/99756c20-9c05-11e4-99ef-0aac01361f0b.png)
I tried those above, and still the same thing :/

**Comment by Buttys** [comment]
http://i.imgur.com/WaQKBfk.png

**Comment by Chahine2** [comment]
When i click Rebuild, it works fine!
